name: windows 10 打包工作流


on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  mc_fishing_opencv:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 跑起来~
        run: |

          python -m pip install -U virtualenv
          virtualenv .venv/
          .venv/Scripts/activate

          python -m pip install -U pip
          pip install pyinstaller>=6.3

          cd mc-fishing-opencv/

          pip install -r requirements-windows.txt
          echo "==================="
          pyinstaller mc-fishing.spec
          echo "==================="
          # cd dist
          # python -m zipfile -c ../mc-fishing.zip mc-fishing/
          
      - name: 保存到工件
        uses: actions/upload-artifact@v4
        with:
          name: mc-fishing-windows
          path: mc-fishing-opencv/dist/mc-fishing/

